version: '3.7'

services:

  flask:
    build: ./flask-server
    image: flask-local
    container_name: flask
    # platform: linux/amd64
    restart: always
    env_file:
      ./env/flask-server.env
    ports:
      - "8000:8000"
    command: gunicorn server:app -w 2 --threads 2 -b 0.0.0.0:8000 --timeout 0

  nginx:
    build: ./nginx
    image: nginx-local
    container_name: nginx
    # platform: linux/amd64
    restart: always
    ports:
      - '80:80'
    depends_on:
      - flask
